### ISSUE TITLE
Task2

### ISSUE THREAD

**Issue by SemenMartynov** [alexandervashurov/json_form#4]
Go ahead and implement the 2nd task.

**Comment by SemenMartynov** [comment]
Any updates?

**Comment by SemenMartynov** [comment]
There is no updates in project documentation, I don't know how to build and run this.

**Comment by SemenMartynov** [comment]
Can you fix your documentation please?

**Comment by SemenMartynov** [comment]
Any updates with this (and others) task?

**Comment by alexandervashurov** [comment]
All tasks already completed

**Comment by SemenMartynov** [comment]
Nope) I don't see your commits. Please, follow gitflow.

**Comment by alexandervashurov** [comment]
task 2 https://github.com/alexandervashurov/json_form/pull/8
fix exception handling https://github.com/alexandervashurov/json_form/pull/12
task 3 https://github.com/alexandervashurov/json_form/pull/11

**Comment by SemenMartynov** [comment]
Yes, all looks good, but we talked about it a few times at the seminars: please follow the task conditions, and then I can check. And I didn't create an issue for the 3rd task.

**Comment by alexandervashurov** [comment]
Please, can you describe conditions

**Comment by alexandervashurov** [comment]
I thougthd that i ve done everything

**Comment by SemenMartynov** [comment]
Well, now you need to rollback your repo, then fix all issues and follow gitflow. Don't forget to link commits with issues.

**Comment by alexandervashurov** [comment]
добрый вечер, я не понимаю. Я еще давно откатил репозиторий,  я создал для второго таска ветку, сделал ишшью, обновил документацию, закрыл ветку. Что не так?

**Comment by SemenMartynov** [comment]
You can create as many issues as you need. I do not receive notifications on them. You do it only for your convenience.
I expect that you will complete the tasks for the issues that I set. According to the terms of the assignment, you must:
1. to follow the gitflow (feature-branches for the each issues)
2. to link your solution with the issue via git commit

Once you're done with this, I can verify that you've learned to use git.

**Comment by alexandervashurov** [comment]
Check now please

**Comment by SemenMartynov** [comment]
I see your commits for #3, for #9... What prevents you from doing the same thing here?)

**Comment by SemenMartynov** [comment]
And we have been discussing for a month, but I still do not see how to launch your project the documentation. Rather I see, but it is not correct.
Try to run your project and you'll see everything.

**Comment by alexandervashurov** [comment]
Now will be ok, all should work

**Comment by SemenMartynov** [comment]
Ok, but can you fix your documentation? -- that is what i'm asking for a month!))
https://github.com/alexandervashurov/json_form/issues/4#issuecomment-365065232

We didn't set how to build and run project with gradle. so I wait for this information in documentation...

**Comment by alexandervashurov** [comment]
Please check documentation now

**Comment by SemenMartynov** [comment]
ok
