### ISSUE TITLE
Exception from main()

### ISSUE THREAD

**Issue by SemenMartynov** [alexandervashurov/json_form#9]
Who is going to catch this exception?

https://github.com/alexandervashurov/json_form/blob/8a9b0ea5dc4741d351c128b0e1926a72cd15186c/src/main/java/Formatter.java#L73

**Comment by alexandervashurov** [comment]
Nobody going to catch this exception

**Comment by SemenMartynov** [comment]
Yeap. So, fix this.

**Comment by SemenMartynov** [comment]
Please, fix all issues and do follow the gitflow, then I can check your work.
